<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.15">
  <compounddef id="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_number_exception" kind="class" language="C#" prot="public">
    <compoundname>ClosedXML::Excel::CalcEngine::Exceptions::NumberException</compoundname>
    <basecompoundref refid="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_calc_engine_exception" prot="public" virt="non-virtual">CalcEngineException</basecompoundref>
      <sectiondef kind="private-func">
      <memberdef kind="function" id="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_number_exception_1a7ec242b2a06f9038d31a14414fccf793" prot="private" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type>internal</type>
        <definition>internal NumberException</definition>
        <argsstring>()</argsstring>
        <name>NumberException</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="C:/Users/cverhaar/Coding/ClosedXML/ClosedXML/Excel/CalcEngine/Exceptions/NumberException.cs" line="14" column="1" bodyfile="C:/Users/cverhaar/Coding/ClosedXML/ClosedXML/Excel/CalcEngine/Exceptions/NumberException.cs" bodystart="14" bodyend="16"/>
      </memberdef>
      <memberdef kind="function" id="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_number_exception_1ac99dad0e174dfd448c28a2912df906ee" prot="private" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type>internal</type>
        <definition>internal NumberException</definition>
        <argsstring>(string message)</argsstring>
        <name>NumberException</name>
        <param>
          <type>string</type>
          <declname>message</declname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="C:/Users/cverhaar/Coding/ClosedXML/ClosedXML/Excel/CalcEngine/Exceptions/NumberException.cs" line="18" column="1" bodyfile="C:/Users/cverhaar/Coding/ClosedXML/ClosedXML/Excel/CalcEngine/Exceptions/NumberException.cs" bodystart="18" bodyend="20"/>
      </memberdef>
      <memberdef kind="function" id="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_number_exception_1ae0c95ffdec6cc1454d4887d38bdf4b1b" prot="private" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type>internal</type>
        <definition>internal NumberException</definition>
        <argsstring>(string message, Exception innerException)</argsstring>
        <name>NumberException</name>
        <param>
          <type>string</type>
          <declname>message</declname>
        </param>
        <param>
          <type>Exception</type>
          <declname>innerException</declname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="C:/Users/cverhaar/Coding/ClosedXML/ClosedXML/Excel/CalcEngine/Exceptions/NumberException.cs" line="22" column="1" bodyfile="C:/Users/cverhaar/Coding/ClosedXML/ClosedXML/Excel/CalcEngine/Exceptions/NumberException.cs" bodystart="22" bodyend="24"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
<para>This error can be caused by an invalid argument in an <ref refid="namespace_closed_x_m_l_1_1_excel" kindref="compound">Excel</ref> function or a formula that produces a number too large or too small to be represented in the worksheet. Corresponds to the #NUM! error in <ref refid="namespace_closed_x_m_l_1_1_excel" kindref="compound">Excel</ref> </para>
    </briefdescription>
    <detaileddescription>
<para><simplesect kind="see"><para><ref refid="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_calc_engine_exception" kindref="compound">ClosedXML.Excel.CalcEngine.Exceptions.CalcEngineException</ref></para>
</simplesect>
</para>
    </detaileddescription>
    <inheritancegraph>
      <node id="824">
        <label>NumberException</label>
        <link refid="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_number_exception"/>
        <childnode refid="825" relation="public-inheritance">
        </childnode>
      </node>
      <node id="825">
        <label>CalcEngineException</label>
        <link refid="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_calc_engine_exception"/>
        <childnode refid="826" relation="public-inheritance">
        </childnode>
      </node>
      <node id="826">
        <label>ArgumentException</label>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="827">
        <label>NumberException</label>
        <link refid="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_number_exception"/>
        <childnode refid="828" relation="public-inheritance">
        </childnode>
      </node>
      <node id="828">
        <label>CalcEngineException</label>
        <link refid="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_calc_engine_exception"/>
        <childnode refid="829" relation="public-inheritance">
        </childnode>
      </node>
      <node id="829">
        <label>ArgumentException</label>
      </node>
    </collaborationgraph>
    <location file="C:/Users/cverhaar/Coding/ClosedXML/ClosedXML/Excel/CalcEngine/Exceptions/NumberException.cs" line="13" column="1" bodyfile="C:/Users/cverhaar/Coding/ClosedXML/ClosedXML/Excel/CalcEngine/Exceptions/NumberException.cs" bodystart="12" bodyend="26"/>
    <listofallmembers>
      <member refid="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_calc_engine_exception_1af165d26040b4d3695b2f0ad82ba577b4" prot="protected" virt="non-virtual"><scope>ClosedXML::Excel::CalcEngine::Exceptions::NumberException</scope><name>CalcEngineException</name></member>
      <member refid="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_calc_engine_exception_1a601146d0629d5fb5b4e1252be25fdb57" prot="protected" virt="non-virtual"><scope>ClosedXML::Excel::CalcEngine::Exceptions::NumberException</scope><name>CalcEngineException</name></member>
      <member refid="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_calc_engine_exception_1a220f839bf265c4484fb9574093ea8dd6" prot="protected" virt="non-virtual"><scope>ClosedXML::Excel::CalcEngine::Exceptions::NumberException</scope><name>CalcEngineException</name></member>
      <member refid="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_number_exception_1a7ec242b2a06f9038d31a14414fccf793" prot="private" virt="non-virtual"><scope>ClosedXML::Excel::CalcEngine::Exceptions::NumberException</scope><name>NumberException</name></member>
      <member refid="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_number_exception_1ac99dad0e174dfd448c28a2912df906ee" prot="private" virt="non-virtual"><scope>ClosedXML::Excel::CalcEngine::Exceptions::NumberException</scope><name>NumberException</name></member>
      <member refid="class_closed_x_m_l_1_1_excel_1_1_calc_engine_1_1_exceptions_1_1_number_exception_1ae0c95ffdec6cc1454d4887d38bdf4b1b" prot="private" virt="non-virtual"><scope>ClosedXML::Excel::CalcEngine::Exceptions::NumberException</scope><name>NumberException</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
